#!/bin/sh

tmux new-window
tmux rename-window 'OEJP'
tmux send-keys 'jp' C-m
tmux send-keys 'git checkout main' C-m
tmux send-keys 'vi' C-m
tmux split-window -h
tmux send-keys 'jp' C-m
tmux send-keys 'yarn run dev' C-m
tmux split-window
# tmux split-window -v -t 0 'exec pfoo "rake ts:start"'
# tmux split-window -v -t 1 'exec pfoo'
